# As travis knows to run npm test on node projects, this works automatically
language: node_js
node_js: node
deploy:
  provider: pages
  local_dir: dest
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: laurens.aarnoudse@gmail.com
  name: Laurens
  on:
    branch: website